//ACTION USER
export const SIGNED_IN = 'SIGNED_IN';
//ACTION CARDS
export const GET_CARDS = 'GET_CARDS';
//ACTION LESSONS
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_LESSONS = 'GET_LESSONS';
export const POST_LESSON = 'POST_LESSON';
//ACTION LETTERS
export const GET_LETTERS = 'GET_LETTERS';
//ACTION TRANSLATOR
export const TRANSLATE = 'TRANSLATE';
export const TRANSLATE_REQUEST = 'TRANSLATE_REQUEST';
