//ACTION CARDS
export const GET_CARDS = 'GET_CARDS';
//ACTION LESSONS
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_LESSONS = 'GET_LESSONS';
export const POST_LESSON = 'POST_LESSON';
//ACTION LETTERS
export const GET_LETTERS = 'GET_LETTERS';
